CREATE TABLE IF NOT EXISTS Users (
  ID SERIAL NOT NULL,
  Name VARCHAR(255),
  Email VARCHAR(255),
  ContactNumber VARCHAR(13),
  Role VARCHAR(10),
  LibID INT,
  PRIMARY KEY (ID),
  FORIEGN KEY (LibID) REFERENCES Library (ID)
);
